### ISSUE TITLE
Non-deterministic results from `noThunksInValues`

### ISSUE THREAD

**Issue by sjakobi** [input-output-hk/nothunks#15]
I'm getting non-deterministic results for a regression test in `unordered-containers`.

You can find the code at https://github.com/sjakobi/unordered-containers/tree/nothunks-issue. Run the test with

```
$ cabal run tests -- -p issue383
```

With GHC 9.2.2 I'm getting failures and successes in roughly equal proportion.

If I remove the source of randomness in the test with

```diff
--- a/tests/Regressions.hs
+++ b/tests/Regressions.hs
@@ -198,7 +198,7 @@ instance Functor MyIdentity where
 
 issue383 :: Assertion
 issue383 = do
-  i :: Int <- randomIO
+  let i :: Int = 42
   let f Nothing = MyIdentity (Just (show i))
       f Just{}  = MyIdentity (error "Nah")
   let (MyIdentity m) = HMS.alterF f () mempty
```

… I get consistent successes with GHC 9.2.2 and consistent failures with GHC 9.0.2.

The expected test result is a success, independent of the value of `i`.

**Comment by sjakobi** [comment]
> Isn't order of evaluation of pure values in Haskell non-deterministic by design?

Surely GHC can be surprisingly eager to evaluate values in some cases, when demand analysis figures out that the value will be forced anyway.

But in this case I don't see much reason for it. The strict let-binding should force the string to the outer `(:)` constructor and no further before `noThunks` is applied.

**Comment by TeofilC** [comment]
I think this is explained by the show instance for `Int`.
It looks like for a negative number forcing the result to whnf gives you `'-': _` whereas for a non-negative number you get the whole number.

Eg, the following ghci session:
```
> showWhnf :: Int -> IO String; showWhnf = evaluate . show
> x1 <- showWhnf 1
> :sprint x1
x1 = "1"
> x2 <- showWhnf $ -1
> :sprint x2
x2 = '-' : _
>
```

**Comment by sjakobi** [comment]
Ha, that explains it! :) Thank you, @TeofilC!
