### ISSUE TITLE
0.1.3 violates PVP

### ISSUE THREAD

**Issue by phadej** [input-output-hk/nothunks#17]
The flags introduced in that release are automatic, therefore solver can turn them off on will. And it very much does with later GHCs, as `text` bound is `<1.3`.

So one cannot rely that `Text`, `Vector` and `ByteString` instances exist.

These flags should have been manual, and `0.1.3` release kind of violates PVP as it allows removal of the instances. Reverse dependency packages **have no way** to ensure the instances exist.

**Comment by erikd** [comment]
@phadej What do you suggest we do? A new `0.2.0` release and deprecate `0.1.3` ?

**Comment by phadej** [comment]
@erikd yes.

**Comment by michaelpj** [comment]
Here's an example where this came up recently. `vector-0.13` was released. This led to us losing the vector instances, because cabal prefers to pick `vector-0.13` and turn off the `vector` flag in nothunks. Whereas I want the constraint to go the other way: I need the vector instances, so I want cabal to be forced to pick `vector < 0.13`.

**Comment by michaelpj** [comment]
This is still a problem.

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision allowing `text-2.0` and `vector-0.13`, which should suffice for now. 
https://hackage.haskell.org/package/nothunks-0.1.3/revisions/

**Comment by michaelpj** [comment]
Just to be clear, I think the issue will recur if `vector-0.14` is released.

**Comment by phadej** [comment]
... or [`text-2.2`](https://github.com/haskell/text/blob/3f26df887b9dfd162c1ac9d315ea642e8c247d35/text.cabal#L1)

**Comment by phadej** [comment]
Or `text-2.1` (as there is already merged [breaking change](https://github.com/haskell/text/pull/474) in `text`s master).

**Comment by phadej** [comment]
As a Hackage trustee I'll make a blacklisting `base <0` revision. It have been six months to fix the issue.

**Comment by coot** [comment]
`nothunks-0.1.4.0` is on [hackage](https://hackage.haskell.org/package/nothunks-0.1.4).

**Comment by coot** [comment]
I also published a new revision of `nothunks-0.1.3` with `base <0`.
